# Generated by Django 2.0.4 on 2018-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemorySentence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(unique=True, verbose_name='英文句子'),
        ),
    ]
